### ISSUE TITLE
Allow Org Tests to Create Transformations Dynamically

### ISSUE THREAD

**Issue by paulknebulaconsulting** [aidan-harding/nebula-object-transformer#10]
Could we open up the @TestVisible methods on the Transformation class to allow tests within the org to create these transformations dynamically?

When I try, I get an error: 
Method is not visible: void nebc.Transformation.<init>(List<nebc__Transformation_Field__mdt>, System.Type)

https://github.com/aidan-harding/nebula-object-transformer/blob/af1db2e933ca621a7ee240351b5fa217a904a90a/force-app/main/default/classes/Transformation.cls#L46

**Comment by aidan-harding** [comment]
Thanks, Paul

It's a fair point - I've actually already done this, but not packaged the change or pushed the commit. I was waiting to sort out #9 first. #9 is sorted now (by a change in Nebula Core), so I'll build this package now with the change you want and an updated Nebula Core dependency.

**Comment by aidan-harding** [comment]
Released in v1.0.4
