### ISSUE TITLE
Add getDestinationFields method

### ISSUE THREAD

**Issue by paulknebulaconsulting** [aidan-harding/nebula-object-transformer#11]
Similar to the getSourceFields method, getDestinationFields return a set of destination fields.
This would allow queries to be done against the destination records, so when transformations are merging data into the destination, we'd already have existing fields queried and could perform a check to see if the fields have changed to do updates on different instead of all records.

**Comment by DanBeerNebula** [comment]
This would be useful - I think I had something similar in my object mapper package.

**Comment by aidan-harding** [comment]
This is the one that made me start updating this package 😃
