### ISSUE TITLE
Transformer fails when source fields contain a hyphen

### ISSUE THREAD

**Issue by DanBeerNebula** [aidan-harding/nebula-object-transformer#9]
See example tests:

@IsTest
    static void thisDoesntWork() {
        /*List<nebc__Transformation_Field__mdt> transformationFieldMetadata = new List<nebc__Transformation_Field__mdt> {
                new nebc__Transformation_Field__mdt(nebc__Source_Field__c = 'first-name', nebc__Target_Field__c = 'FirstName'),
                new nebc__Transformation_Field__mdt(nebc__Source_Field__c = 'last-id', nebc__Target_Field__c = 'LastName')
        }*/

        nebc.Transformation thisTransformation = new nebc.Transformation('Test_Contact', Contact.class);

        Map<String, Object> myContact = new Map<String, Object>{
                'first-name' => 'Eric',
                'last-id' => 'Cantona'
        };

        Contact eric = (Contact) thisTransformation.call(myContact);

        Assert.areEqual('Eric', eric.FirstName);
        Assert.areEqual('Cantona', eric.LastName);

    }

    @IsTest
    static void thisDoes() {
        /*List<nebc__Transformation_Field__mdt> transformationFieldMetadata = new List<nebc__Transformation_Field__mdt> {
                new nebc__Transformation_Field__mdt(nebc__Source_Field__c = 'first_name', nebc__Target_Field__c = 'FirstName'),
                new nebc__Transformation_Field__mdt(nebc__Source_Field__c = 'lastId', nebc__Target_Field__c = 'LastName')
        }*/

        nebc.Transformation thisTransformation = new nebc.Transformation('Test_Contact', Contact.class);

        Map<String, Object> myContact = new Map<String, Object>{
                'first_name' => 'Eric',
                'lastId' => 'Cantona'
        };

        Contact eric = (Contact) thisTransformation.call(myContact);

        Assert.areEqual('Eric', eric.FirstName);
        Assert.areEqual('Cantona', eric.LastName);

    }

**Comment by aidan-harding** [comment]
Released in v1.0.4 by requiring the new version of Nebula Core that fixes the underlying bug
